# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# test

trigger:
- master

pool: mypool

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'AspNetCoreWebApplication/AspNetCoreWebApplication.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-c release'

- script: tar -czvf package.tgz AspNetCoreWebApplication/wwwroot/**/* AspNetCoreWebApplication/bin/**/* scripts/* appspec.yml mytemplate.yml params.json
  displayName: 'Packaging to tgz'

- task: S3Upload@1
  inputs:
    awsCredentials: 'aws-service-conn'
    regionName: 'ca-central-1'
    bucketName: 'husky-rentals-bucket-1'
    globExpressions: 'package.tgz'
    targetFolder: 'packaged-artifact'

- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'aws-service-conn'
    regionName: 'ca-central-1'
    stackName: 'az-stack'
    templateSource: 'file'
    templateFile: 'mytemplate.yml'
    templateParametersFile: 'params.json'
    capabilityAutoExpand: true

